webapp/src/Entity/Films.php
<?php

namespace App\Entity;

use App\Repository\FilmsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmsRepository::class)]
class Films
{
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column]
	private ?int $id = null;

	#[ORM\Column(length: 80)]
	private string $titre;

	#[ORM\Column(length: 255, nullable: true)]
	private ?string $affiche = null;

	#[ORM\Column(type: Types::TEXT)]
	private string $description;

	#[ORM\Column(type: Types::JSON)]
	private array $genre = [];

	#[ORM\Column]
	private ?int $age_mini = null;

	#[ORM\Column(nullable: true)]
	private ?int $coup_de_coeur = null;

	#[ORM\Column(nullable: true)]
	private ?int $score = null;

	#[ORM\Column(type: Types::TIME_MUTABLE)]
	private \DateTimeInterface $duree;

	#[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
	private \DateTimeImmutable $date_ajout;

	/**
	 * @var Collection<int, Avis>
	 */
	#[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'film_id', orphanRemoval: true)]
	private Collection $notes;

	/**
	 * @var Collection<int, Seances>
	 */
	#[ORM\OneToMany(targetEntity: Seances::class, mappedBy: 'film_id', orphanRemoval: true)]
	private Collection $seances;

	#[ORM\Column(length: 100, nullable: true)]
	private ?string $realisateur = null;

	#[ORM\Column(length: 255, nullable: true)]
	private ?string $acteurs = null;

	#[ORM\Column(length: 255, nullable: true)]
	private ?string $avertissement = null;

	public function __construct()
	{
		$this->notes = new ArrayCollection();
		$this->seances = new ArrayCollection();
	}

	public function getId(): ?int
	{
		return $this->id;
	}


	public function __toString(): string
	{
		return $this->getTitre();
	}

	public function getTitre(): string
	{
		return $this->titre;
	}

	public function setTitre(string $titre): static
	{
		$this->titre = $titre;

		return $this;
	}

	public function getAffiche(): ?string
	{
		return $this->affiche;
	}

	public function setAffiche(?string $affiche): static
	{
		$this->affiche = $affiche;

		return $this;
	}

	public function getDescription(): string
	{
		return $this->description;
	}

	public function setDescription(string $description): static
	{
		$this->description = $description;

		return $this;
	}

	public function getGenre(): array
	{
		return $this->genre;
	}

	public function setGenre(array $genre): static
	{
		$this->genre = $genre;

		return $this;
	}

	public function getAgeMini(): ?int
	{
		return $this->age_mini;
	}

	public function setAgeMini(int $age_mini): static
	{
		$this->age_mini = $age_mini;

		return $this;
	}

	public function getCoupDeCoeur(): bool
	{
		if ($this->coup_de_coeur === 1)
			return true;
		else
			return false;
	}

	public function setCoupDeCoeur(?int $coup_de_coeur): static
	{
		$this->coup_de_coeur = $coup_de_coeur;

		return $this;
	}

	public function getScore(): ?int
	{
		return $this->score;
	}

	public function setScore(?int $score): static
	{
		$this->score = $score;

		return $this;
	}

	public function getDuree(): ?\DateTimeInterface
	{
		return $this->duree;
	}

	public function getDureeStr(): string
	{
		return $this->duree->format('G:i');
	}

	public function getDureeMinutes(): int
	{
		$heures = intval($this->duree->format('G'));
		$minutes = intval($this->duree->format('i'));
		return ($heures * 60) + $minutes;
	}

	public function setDuree(\DateTimeInterface $duree): static
	{
		$this->duree = $duree;

		return $this;
	}

	public function getDateAjout(): \DateTimeImmutable
	{
		return $this->date_ajout;
	}

	public function setDateAjout(\DateTimeImmutable $date_ajout): static
	{
		$this->date_ajout = $date_ajout;

		return $this;
	}

	/**
	 * @return Collection<int, Avis>
	 */
	public function getNotes(): Collection
	{
		return $this->notes;
	}

	public function addNote(Avis $note): static
	{
		if (!$this->notes->contains($note)) {
			$this->notes->add($note);
			$note->setFilmId($this);
		}

		return $this;
	}

	public function removeNote(Avis $note): static
	{
		if ($this->notes->removeElement($note)) {
			// set the owning side to null (unless already changed)
			if ($note->getFilmId() === $this) {
				$note->setFilmId(null);
			}
		}

		return $this;
	}

	/**
	 * @return Collection<int, Seances>
	 */
	public function getSeances(): Collection
	{
		return $this->seances;
	}

	public function addSeance(Seances $seance): static
	{
		if (!$this->seances->contains($seance)) {
			$this->seances->add($seance);
			$seance->setFilmId($this);
		}

		return $this;
	}

	public function removeSeance(Seances $seance): static
	{
		if ($this->seances->removeElement($seance)) {
			// set the owning side to null (unless already changed)
			if ($seance->getFilmId() === $this) {
				$seance->setFilmId(null);
			}
		}

		return $this;
	}

	public function getRealisateur(): ?string
	{
		return $this->realisateur;
	}

	public function setRealisateur(?string $realisateur): static
	{
		$this->realisateur = $realisateur;

		return $this;
	}

	public function getActeurs(): ?string
	{
		return $this->acteurs;
	}

	public function setActeurs(?string $acteurs): static
	{
		$this->acteurs = $acteurs;

		return $this;
	}

	public function getAvertissement(): ?string
	{
		return $this->avertissement;
	}

	public function setAvertissement(?string $avertissement): static
	{
		$this->avertissement = $avertissement;

		return $this;
	}

	public function getAnciennete(): string
	{
		return $this->getDateAjout()->diff(new \DateTime("now"))->days;
	}

}

webapp/src/Entity/Salles.php
<?php

namespace App\Entity;

use App\Repository\SallesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SallesRepository::class)]
class Salles
{
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column]
	private ?int $id = null;

	#[ORM\Column]
	private int $places;

	#[ORM\Column]
	private array $technologies = [];

	#[ORM\Column(length: 45)]
	private string $salle_nom;

	#[ORM\ManyToOne(inversedBy: 'salles')]
	#[ORM\JoinColumn(nullable: false)]
	private Cinemas $cinema_id;

	/**
	 * @var Collection<int, Seances>
	 */
	#[ORM\OneToMany(targetEntity: Seances::class, mappedBy: 'salle_id', orphanRemoval: true)]
	private Collection $seances;

	public function __construct()
	{
		$this->seances = new ArrayCollection();
	}

	public function getId(): ?int
	{
		return $this->id;
	}


	public function __toString(): string
	{
		return $this->getSalleNom();  // or some string field in your Vegetal Entity
	}


	public function getPlaces(): int
	{
		return $this->places;
	}

	public function setPlaces(int $places): static
	{
		$this->places = $places;

		return $this;
	}

	public function getTechnologies(): array
	{
		return $this->technologies;
	}

	public function setTechnologies(array $technologies): static
	{
		$this->technologies = $technologies;

		return $this;
	}

	public function getSalleNom(): string
	{
		return $this->salle_nom;
	}

	public function setSalleNom(string $salle_nom): static
	{
		$this->salle_nom = $salle_nom;

		return $this;
	}

	public function getCinemaId(): Cinemas
	{
		return $this->cinema_id;
	}

	public function setCinemaId(Cinemas $cinema_id): static
	{
		$this->cinema_id = $cinema_id;

		return $this;
	}

	/**
	 * @return Collection<int, Seances>
	 */
	public function getSeances(): Collection
	{
		return $this->seances;
	}

	public function addSeance(Seances $seance): static
	{
		if (!$this->seances->contains($seance)) {
			$this->seances->add($seance);
			$seance->setSalleId($this);
		}

		return $this;
	}

	public function removeSeance(Seances $seance): static
	{
		if ($this->seances->removeElement($seance)) {
			// set the owning side to null (unless already changed)
			if ($seance->getSalleId() === $this) {
				$seance->setSalleId(null);
			}
		}

		return $this;
	}
}

webapp/src/Entity/Seances.php
<?php

namespace App\Entity;

use App\Repository\SeancesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SeancesRepository::class)]
class Seances
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTimeInterface $date_debut;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTimeInterface $date_fin;

    #[ORM\ManyToOne(inversedBy: 'seances')]
    #[ORM\JoinColumn(nullable: false)]
    private Films $film_id;

    #[ORM\ManyToOne(inversedBy: 'seances')]
    #[ORM\JoinColumn(nullable: false)]
    private Salles $salle_id;

    #[ORM\Column]
    private ?int $cinema_id = null;
    private ?int $duree_film = null;

    #[ORM\Column(nullable: true)]
    private ?array $technologies = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): \DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): \DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getFilmId(): Films
    {
        return $this->film_id;
    }

    public function setFilmId(Films $film_id): static
    {
        $this->film_id = $film_id;

        return $this;
    }

    public function getDureeFilm(): int
    {
        return $this->duree_film;
    }

    public function setDureeFilm(int $duree_film): static
    {
        $this->duree_film = $duree_film;
        return $this;
    }

    public function getSalleId(): Salles
    {
        return $this->salle_id;
    }

    public function setSalleId(Salles $salle_id): static
    {
        $this->salle_id = $salle_id;

        return $this;
    }

    public function getCinemaId(): ?int
    {
        return $this->cinema_id;
    }

    public function setCinemaId(int $cinema_id): static
    {
        $this->cinema_id = $cinema_id;

        return $this;
    }

    public function getTechnologies(): ?array
    {
        return $this->technologies;
    }

    public function setTechnologies(?array $technologies): static
    {
        $this->technologies = $technologies;

        return $this;
    }
}

webapp/templates/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="col-12 px-6 align-items-center">

   <div id="carouselExample" class="carousel slide mx-auto" data-bs-theme="light" data-bs-ride="carousel">
      <div class="carousel-inner">
         
         {% set loop_index = 0 %}
         
         {% for film in films %}
            {% if film.coupDeCoeur == 1 %}
               {% set loop_index = loop_index + 1 %}
               {% if loop_index == 1 %}
                  {% set is_active = "active" %}
               {% else %}
                  {% set is_active = "" %}
               {% endif %}
               
               <div class="carousel-item {{ is_active }}">
                  <img src="images/bannieres/{{ film.affiche }}.jpg" class="d-block w-100" alt="{{ film.titre }}">
               </div>
               
            {% endif %}
            
         {% endfor %}
         
         
      </div>
      <button class=" owl-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
         <span aria-label="Previous" >‹</span>
      </button>
      <button class="carousel-control-next owl-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
         <span aria-label="Next">›</span>
      </button>
   </div>
   
   
   
   <h1 class="accueil">FILMS A L'AFFICHE</h1>
   
   
   <div class="affiches_carousel mx-auto">
      <div class="owl-carousel">
         
         {% for film in films %}
         <div class="affiche">
            <a href="/film/{{ film.id }}" title="{{ film.titre }}" class="lien_affiche">
               <img class="img-fluid mx-auto d-block images_affiches" src="/images/affiches/{{ film.affiche }}.jpg" alt="{{ film.titre }}">
               <p class="titre_film">{{ film.titre }}</p>
            </a>
         </div>
         {% else %}
            
            <div class="affiche">Aucun film trouvé !</div>
         
         {% endfor %}
         
      </div>

   </div>
</div>


{% endblock %}

{% block scripts_supp %}
   <script src="/js/owl.carousel.js"></script>
   <script>
       $(document).ready(function(){
           $(".owl-carousel").owlCarousel({
               center: true,
               items:2,
               loop:true,
               margin:15,
               nav: true,
               dots: false,
               responsive:{
                   600:{
                       items:3
                   },
                   800:{
                       items:4
                   },
                   1000:{
                       items:5
                   },
                   1200:{
                       items:6
                   },
                   1400:{
                       items:7
                   },
                   1600:{
                       items:8
                   },
                   1800:{
                       items:9
                   }
               }
           });
       });
   </script>
{% endblock %}

webapp/templates/cinemas.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos cinémas{% endblock %}

{% block content %}
    
    <div class="col-12 mx-auto px-5 py-3 my-3 mb-0 align-items-center page_cinemas">
        
        <div class="card text-bg-dark mb-3 mx-auto">
            
            <div class="card-header fs-5"><h2>{{ block('title') }}</h2></div>
            <div class="card-body p-5 ">
                <h5 class="text-success-emphasis mb-5">Cinéphoria vous propose 5 cinémas en France, et 2 en Belgique :</h5>
                
                
                {% for cinema in cinemas %}
                <div class="row mb-5">
                    <div class="col-12">
                        <img src="images/{{ cinema.nom|slug|lower }}.jpg" class="img-fluid float-end pb-3" alt="{{ cinema.nom }}">
                        
                        <h3>{{ cinema.nom }}</h3>
                        
                        <p>{{ cinema.adresse1 }} </p>
                        <p>{{ cinema.cp }} {{ cinema.ville }}</p>
                    
                    </div>
                </div>
                {% endfor %}
            
            </div>
        </div>
    </div>


{% endblock %}

webapp/templates/contact.html.twig
{% extends 'base.html.twig' %}

        {% block title %}Nous contacter{% endblock %}

{% block content %}

<div class="col-12 px-5 py-3 my-3 mb-0 align-items-center">
    
    <div class="card text-bg-dark mb-3 mx-auto" style="max-width: 875px;">
        
        <div class="card-header fs-5"><h2>{{ block('title') }}</h2></div>
        <div class="card-body p-5 ">
        

    <form action="#" method="post">
        
        <div class="row align-items-start mb-3">
            <div class="col-md-12 px-5">
                
                <div class="mb-3">
                    <label for="nom" class="form-label">Votre Nom :</label>
                    <input type="text" class="form-control" name="nom" id="nom" aria-describedby="Nom">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Votre Email :</label>
                    <input type="email" class="form-control" name="email" id="email" aria-describedby="Email">
                </div>
                <div class="mb-3">
                    <label for="message" class="form-label">Votre message :</label>
                    <textarea class="form-control" name="message" id="message" aria-describedby="Message" rows="5"></textarea>
                </div>
                <p class="text-center text-warning">Veuillez noter que pour le moment, ce formulaire ne fonctionne pas.</p>
                <div class="mb-3 text-center">
                    <button type="submit" class="btn btn-success rounded-pill my-4 px-5 fs-5 open-sans-bold shadow">Envoyer</button>
                </div>
            
            </div>
            
        </div>
    
    </form>
    
    </div>
    </div>
    </div>

{% endblock %}

webapp/templates/film_details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="col-12 px-6 conteneur_general_film">
   
   <div class="conteneur_banniere">
      <img src="/images/bannieres/{{ film.affiche }}.jpg" class="align-self-center img-fluid image_banniere" alt="{{ film.titre }}">
   </div>
   
   <div class="conteneur_details_film">
      
      <div class="zone_titre">
         <h1 class="mt-3 film_details_titre">{{ film.titre }}</h1>
         
         <div class="duree_badges">
            {% if film.ageMini == 0 %}
              {% set mention_age_public = "Tous publics" %}
              {% set badge_class = "text-bg-success" %}
            {% elseif film.ageMini < 12 %}
              {% set mention_age_public = "A partir de " ~ film.ageMini ~ " ans" %}
              {% set badge_class = "text-bg-primary" %}
            {% elseif film.ageMini >= 12 %}
              {% set mention_age_public = "Interdit aux moins de " ~ film.ageMini ~ " ans" %}
              {% set badge_class = "text-bg-warning" %}
            {% elseif film.ageMini >= 18 %}
              {% set mention_age_public = "Interdit aux moins de " ~ film.ageMini ~ " ans" %}
              {% set badge_class = "text-bg-danger" %}
            {% endif %}
            
            {% set mention_avertissement = "" %}
            {% set basdge_avertissement = "" %}
            {% if film.avertissement != "" %}
               {% set mention_avertissement = "Avertissement : " %}
            {% endif %}
            
            <p class="details_film fs-5">
               <span>Durée :</span> {{ film.duree|format_time(pattern: "h'h' mm") }} &nbsp;
               <span class="badge  {{ badge_class }}">{{ mention_age_public }}</span>
               {% if film.avertissement != "" %}
                  <span class="badge text-bg-primary">Avec avertissement</span>
               {% endif %}
               {% if film.coupDeCoeur %}
                  &nbsp; &nbsp; <i class="bi-heart-fill text-danger" title="Coup de coeur Cinéphoria !"></i>
               {% endif %}
            </p>
         
         </div>
      </div>
      
      
      <div class="zone_details">
         <p class="details_film"><span>Genre :</span>
            
            {% for genre in film.genre %}
               {% set separateur = not loop.last ? ", " : "" %}
               {{ genres[genre] }}{{ separateur }}
            {% endfor %}
            
         </p>
         
         <p class="details_film"><span>Date de sortie :</span> {{ film.dateAjout|format_date('long') }}</p>
         <p class="details_film"><span>Réalisé par :</span> {{ film.realisateur }}</p>
         <p class="details_film"><span>Avec :</span> {{ film.acteurs }}</p>
      </div>
      
      
      <div class="zone_description">
         <p class="card-text">{{ film.description }}</p>
         <p class="card-text fw-bold">{{ mention_avertissement }}{{ film.avertissement }}</p>
      </div>
      
      
      <div class="zone_seances">
         <div class="row justify-content-center">
            <div class="col-12">
              {% set date_aujourdhui = date()|format_date('long')  %}
            
               <h3 class="text-center">Les séances d'aujourd'hui, {{ date_aujourdhui }}</h3>
               <p class="text-center">
                  {% for seance in film.seances %}
                     
                     {% set class_badge = "text-bg-primary" %}
                     {% if seance.dateDebut < date() %}
                        {% set class_badge = "text-bg-danger text-decoration-line-through opacity-25" %}
                     {% endif %}
                     
                     
                     {% if seance.dateDebut|format_date('long') == date_aujourdhui %}
                     {% if seance.cinemaId == 1 %}
                           <span class=" badge {{ class_badge }} fs-4 px-3 mx-3">{{ seance.dateDebut|format_time('short') }}</span>
                     {% endif %}
                  {% endif %}
                  
                  {% else %}
                     <span class=" badge text-bg-warning fs-4 px-3 mx-3">Aucune séance aujourd'hui</span>
                  {% endfor %}
               </p>
            </div>
         </div>
      </div>
      
      
      <div class="zone_affiche">
         <img src="/images/affiches/{{ film.affiche }}.jpg" class="img-fluid  image_affiche_details" alt="{{ film.titre }}">
      </div>
      
   </div>
</div>


{% endblock %}

{% block scripts_supp %}

{% endblock %}

webapp/templates/films.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="col-12 px-6 conteneur_general_film">
   
   <div class="row filtres_films">
      <div class="col-12 p-0">
         <div class="dropdown choix_cinema">
            <button class="btn btn-primary dropdown-toggle w-100 dropdown_cinemas" type="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
              Aujourd'hui dans votre : Veuillez choisir un cinéma
            </button>
            <ul class="dropdown-menu fs-4 w-100 text-center">
               <li><h6 class="dropdown-header">Cinémas en France</h6></li>
               
               {% for cinema in cinemas %}
                  {% if "Belgique" not in cinema.ville %}
                     <li><a class="dropdown-item lien_filtre_cinema" data-cinema-id="{{ cinema.id }}">{{ cinema.nom }}</a></li>
                  {% endif %}
               {% endfor %}
               
               <li><hr class="dropdown-divider"></li>
               <li><h6 class="dropdown-header">Cinémas en Belgique</h6></li>
               {% for cinema in cinemas %}
                  {% if "Belgique" in cinema.ville %}
                     <li><a class="dropdown-item lien_filtre_cinema" data-cinema-id="{{ cinema.id }}">{{ cinema.nom }}</a></li>
                  {% endif %}
               {% endfor %}
            </ul>
         </div>
      </div>
      
      <div class="col-12 ligne_filtres">
         <div class="filtres_jours">
            <ul class="nav nav-underline nav_filtres px-3 ps-0">
               {% for date_key, jour_fr in dates %}
                  {% set class_active = (loop.index == 1) ? "active" : "" %}
                  <li class="nav-item">
                     <a class="nav-link {{ class_active }} lien_filtre_date lien_j{{ loop.index }}" data-filtre-date="{{ date_key }}" data-nom-jour="j{{ loop.index }}">{{ jour_fr }}</a>
                  </li>
               {% endfor %}
            </ul>
         </div>
         
         <div class="filtres_menu">
            <ul class="nav nav-underline nav_filtres px-3 pe-0">
               <li class="nav-item">
                  <a class="nav-link lien_voir_tout active" data-filtres="voir_tout">Voir tout</a>
               </li>
               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle dropdown_filtres" data-bs-toggle="dropdown" role="button" aria-expanded="false" data-bs-auto-close="outside">
                     Filtres
                  </a>
                  <ul class="dropdown-menu">
                     <li><h6 class="dropdown-header">Technologies</h6></li>
                     <li>
                           <span class="badge rounded-pill badge_genre_filtres badge_filtre_techno" data-filtre-techno="4DX">4DX-ICE</span>
                           <span class="badge rounded-pill badge_genre_filtres badge_filtre_techno" data-filtre-techno="3D">3D</span>
                           <span class="badge rounded-pill badge_genre_filtres badge_filtre_techno" data-filtre-techno="IMAX">IMAX</span>
                           <span class="badge rounded-pill badge_genre_filtres badge_filtre_techno" data-filtre-techno="ONYX">ONYX</span>
                     </li>
                     
                     <li><hr class="dropdown-divider"></li>
                     <li><h6 class="dropdown-header">Genres</h6></li>
                     <li>
                        {% for genre_key, genre in genres %}
                           <span class="badge rounded-pill badge_genre_filtres badge_filtre_genre" data-filtre-genre="{{ genre_key }}">{{ genre }}</span>
                        {% endfor %}
                     </li>
                  
                  </ul>
               </li>
            </ul>
         </div>
         
      </div>
   </div>
   
   
   <div class="row g-2 g-sm-3 g-lg-4 mt-1 px-2 row-cols-2 row-cols-md-3 row-cols-xl-4 row-cols-xxl-5  liste_films">
   
   {% for film in films %}
      <div class="col div_film">
         <a href="/film/{{ film.id }}" class="films_lien_details">
            <div class="card">
                  <img src="images/affiches/{{ film.affiche }}.jpg" class="card-img-top" alt="{{ film.titre }}">
                  <div class="film_hover">
                     INFOS ET<br><b>SEANCES</b>
                  </div>
               
               {% set startDate = film.dateAjout %}
               {% set difference = date( 'now' | date() ).diff(date(startDate)) %}
               {% set difference_jours = difference.days %}
               {% if difference_jours < 7 %}
                  <span class="badge text-bg-danger fs-5 position-absolute top-0 start-0 mt-4 ms-2">NOUVEAU</span>
               {% endif %}
               
               {% if film.ageMini > 0 or film.avertissement != "" or film.coupDeCoeur %}
                  {% set mention_age_public = "-" ~ film.ageMini %}
                  
                  {% if film.ageMini < 12 %}
                     {% set badge_class = "text-bg-primary" %}
                     {% set badge_info = "A partir de " ~ film.ageMini ~ " ans" %}
                  {% elseif film.ageMini >= 12 %}
                     {% set badge_class = "text-bg-warning" %}
                     {% set badge_info = "Interdit aux moins de " ~ film.ageMini ~ " ans" %}
                  {% elseif film.ageMini >= 18 %}
                     {% set badge_class = "text-bg-danger" %}
                     {% set badge_info = "Interdit aux moins de " ~ film.ageMini ~ " ans" %}
                  {% endif %}
                  
                  <span class="fs-5 position-absolute bottom-0 end-0 mb-4 me-2">
                    
                     {% if film.ageMini > 0 %}
                       <span class="badge rounded-pill {{ badge_class }}" title="{{ badge_info }}">{{ mention_age_public }}</span>
                     {% endif %}
                     
                     {% if film.avertissement != "" %}
                        <i class="bi-exclamation-circle-fill" title="Avertissement : {{ film.avertissement }}"></i>
                     {% endif %}
                     
                     {% if film.coupDeCoeur %}
                       <i class="bi-heart-fill text-danger" title="Coup de coeur Cinéphoria !"></i>
                     {% endif %}

                  </span>
               
               {% endif %}
               
               
               
               
               <div class="card-body">
                  <h5 class="card-title">{{ film.titre }}</h5>
               </div>
            </div>
         </a>
      </div>
         {% else %}
            
            <div class="w-100">
               <h4 class="text-center">Aucune séance trouvée ce jour. Essayez de choisir un autre jour !</h4>
            </div>
         
         {% endfor %}
         

   </div>
</div>


{% endblock %}

{% block scripts_supp %}

{% endblock %}

webapp/templates/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="col-12 px-6 align-items-center">
   
         <h1 class="text-center mb-4">Réservation</h1>

</div>


{% endblock %}

{% block scripts_supp %}

{% endblock %}